// <auto-generated />
using EFCore_Transaction;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCore_Transaction.Migrations
{
    [DbContext(typeof(TransactionContext))]
    [Migration("20191129013328_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1");

            modelBuilder.Entity("EFCore_Transaction.Transaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("_Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("_Credit")
                        .HasColumnType("TEXT");

                    b.Property<string>("_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("_Debit")
                        .HasColumnType("TEXT");

                    b.Property<string>("_Description")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
